/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as interfaces from "./interfaces";

export type { interfaces };
export type { SocialNetwork } from "./SocialNetwork";
export * as factories from "./factories";
export type { ISocialNetwork } from "./interfaces/ISocialNetwork";
export { ISocialNetwork__factory } from "./factories/interfaces/ISocialNetwork__factory";
export { SocialNetwork__factory } from "./factories/SocialNetwork__factory";
